# Generated by Django 3.1.1 on 2020-10-11 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('dis', 'Disabled'), ('act', 'Active')], default='act', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('act', 'Active'), ('blo', 'Blocked'), ('ukn', 'Unknown')], default='act', max_length=3)),
                ('balance', models.FloatField(blank=True, default=0.0)),
                ('due_Date', models.DateField()),
                ('trail', models.BooleanField(default=False)),
                ('allow_International_messages', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_Number', models.CharField(blank=True, max_length=15)),
                ('corrlinks_ID', models.CharField(max_length=15)),
                ('corrlinks_Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corrSMS.account')),
            ],
        ),
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VPS_Name', models.CharField(max_length=5)),
                ('notes', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'VPS',
                'verbose_name_plural': 'VPS',
            },
        ),
        migrations.CreateModel(
            name='SMSCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('phone_Number', models.CharField(blank=True, max_length=15)),
                ('corrlinks_Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corrSMS.customer')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='VPS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='corrSMS.vps'),
        ),
    ]
