# Generated by Django 3.1.1 on 2020-10-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corrSMS', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMSCustomer',
        ),
    ]
