# Generated by Django 3.1.1 on 2020-10-11 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corrSMS', '0003_smscustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSToCorrlinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('snt', 'Sent'), ('dis', 'Disabled'), ('err', 'Error')], default='new', max_length=3)),
                ('_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corrSMS.smscustomer')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corrSMS.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CorrlinksToSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('snt', 'Sent'), ('dis', 'Disabled'), ('err', 'Error')], default='new', max_length=3)),
                ('_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corrSMS.customer')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corrSMS.smscustomer')),
            ],
        ),
    ]
