# Generated by Django 3.1.1 on 2020-10-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corrSMS', '0004_corrlinkstosms_smstocorrlinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smstocorrlinks',
            name='to',
        ),
    ]
