# Generated by Django 3.1.1 on 2020-10-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrSMS', '0005_remove_smstocorrlinks_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrlinkstosms',
            name='body',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='smstocorrlinks',
            name='body',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
