# Generated by Django 3.1.1 on 2020-10-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrSMS', '0006_auto_20201011_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API_Key', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterModelOptions(
            name='corrlinkstosms',
            options={'verbose_name': 'Corrlinks To SMS', 'verbose_name_plural': 'Corrlinks To SMS'},
        ),
        migrations.AlterModelOptions(
            name='smstocorrlinks',
            options={'verbose_name': 'SMS To Corrlinks', 'verbose_name_plural': 'SMS To Corrlinks'},
        ),
    ]
