# Generated by Django 3.1.1 on 2020-10-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrSMS', '0009_auto_20201011_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='bandwidth_Message_ID',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
