# Generated by Django 3.1.1 on 2020-10-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corrSMS', '0010_image_bandwidth_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='trail',
        ),
        migrations.RemoveField(
            model_name='smscustomer',
            name='tag',
        ),
    ]
