# Generated by Django 3.1.1 on 2020-10-12 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corrSMS', '0011_auto_20201012_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='corrCustomer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='corrSMS.customer'),
        ),
    ]
