# Generated by Django 2.2.7 on 2020-10-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrSMS', '0012_image_corrcustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='bandwidth_Message_ID',
        ),
        migrations.AlterField(
            model_name='smscustomer',
            name='phone_Number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
