# Generated by Django 3.1.1 on 2020-10-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrSMS', '0013_auto_20201016_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corrlinkstosms',
            name='body',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='smstocorrlinks',
            name='body',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
