# Generated by Django 3.1.1 on 2020-10-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrSMS', '0014_auto_20201018_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrlinkstosms',
            name='bandwidth_ID',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
