# Generated by Django 3.1.1 on 2020-10-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrSMS', '0015_corrlinkstosms_bandwidth_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscustomer',
            name='phone_Number',
            field=models.CharField(max_length=15),
        ),
    ]
