# Generated by Django 3.1.1 on 2020-10-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corrSMS', '0019_auto_20201028_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAndImage',
            fields=[
            ],
            options={
                'verbose_name': "Customer's Picture",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('corrSMS.customer',),
        ),
    ]
